# Generated by Django 5.2.8 on 2025-11-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatecompany',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='realestatecompany',
            name='country',
            field=models.CharField(default='India', max_length=64),
        ),
        migrations.AddField(
            model_name='realestatecompany',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='realestatecompany',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='realestatecompany',
            name='state',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='realestatecompany',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='realestatecompany',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestatecompany',
            name='website',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
