# Generated by Django 5.2.8 on 2025-11-25 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_realestatecompany_city_realestatecompany_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessforsale',
            name='property_type',
            field=models.ForeignKey(blank=True, default=1, help_text='Buy, Rent, Commercial Buy, Commercial Rent, New Project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pro.propertytype'),
        ),
    ]
