# Generated by Django 5.2.8 on 2025-11-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_alter_businessforsale_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessforsale',
            name='locality',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
