# Generated by Django 5.2.8 on 2025-11-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_alter_businessforsale_locality'),  
    ]

    operations = [
        migrations.AlterField(
            model_name='pgproperty',
            name='locality',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
