# Generated by Django 5.2.8 on 2025-11-26 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0005_alter_pgproperty_locality'),  
    ]

    operations = [
        migrations.AlterField(
            model_name='pgproperty',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
