# Generated by Django 5.2.8 on 2025-11-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0009_alter_agricultureproperty_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproperty',
            name='balcony',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commercialproperty',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialproperty',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialproperty',
            name='view',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
