# Generated by Django 5.2.8 on 2025-11-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0010_commercialproperty_balcony_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialpropertyimage',
            name='office_image',
        ),
        migrations.RemoveField(
            model_name='commercialpropertyimage',
            name='showroom_image',
        ),
        migrations.RemoveField(
            model_name='commercialpropertyimage',
            name='warehouse_image',
        ),
        migrations.AddField(
            model_name='commercialpropertyimage',
            name='bathroom_image',
            field=models.ImageField(blank=True, null=True, upload_to='residential/bathroom/'),
        ),
        migrations.AddField(
            model_name='commercialpropertyimage',
            name='bedroom_image',
            field=models.ImageField(blank=True, null=True, upload_to='residential/bedroom/'),
        ),
        migrations.AddField(
            model_name='commercialpropertyimage',
            name='kitchen_image',
            field=models.ImageField(blank=True, null=True, upload_to='residential/kitchen/'),
        ),
        migrations.AddField(
            model_name='commercialpropertyimage',
            name='living_room_image',
            field=models.ImageField(blank=True, null=True, upload_to='residential/living_room/'),
        ),
        migrations.AlterField(
            model_name='commercialpropertyimage',
            name='exterior_image',
            field=models.ImageField(blank=True, null=True, upload_to='residential/exterior/'),
        ),
        migrations.AlterField(
            model_name='commercialpropertyimage',
            name='floor_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='residential/floor_plan/'),
        ),
        migrations.AlterField(
            model_name='commercialpropertyimage',
            name='location_map_image',
            field=models.ImageField(blank=True, null=True, upload_to='residential/location_map/'),
        ),
        migrations.AlterField(
            model_name='commercialpropertyimage',
            name='master_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='residential/master_plan/'),
        ),
    ]
