# Generated by Django 5.2.8 on 2025-11-27 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0011_remove_commercialpropertyimage_office_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricultureproperty',
            name='property_type',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pro.propertytype'),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='property_type',
            field=models.ForeignKey(blank=True, default=3, help_text='Buy, Rent, Commercial Buy, Commercial Rent, New Project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pro.propertytype'),
        ),
    ]
