# Generated by Django 5.2.8 on 2025-11-27 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0012_alter_agricultureproperty_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricultureproperty',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pro.agent'),
        ),
        migrations.AddField(
            model_name='businessforsale',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pro.agent'),
        ),
        migrations.AddField(
            model_name='holidayproperty',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pro.agent'),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pro.agent'),
        ),
    ]
