# Generated by Django 5.2.8 on 2025-11-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0013_agricultureproperty_agent_businessforsale_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='locality',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
