# Generated by Django 5.2.8 on 2025-11-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0014_customuser_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='Plocality',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
