# Generated by Django 5.1.6 on 2025-11-20 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricultureproperty',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Agriculture_Listing', to='pro.realestatecompany'),
        ),
        migrations.AddField(
            model_name='agricultureproperty',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessforsale',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_listings', to='pro.realestatecompany'),
        ),
        migrations.AddField(
            model_name='commercialproperty',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_properties', to='pro.realestatecompany'),
        ),
        migrations.AddField(
            model_name='holidayproperty',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Holiday_Listing', to='pro.realestatecompany'),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PG_Listing', to='pro.realestatecompany'),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='residentialproperty',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residential_properties', to='pro.realestatecompany'),
        ),
    ]
