# Generated by Django 5.1.6 on 2025-11-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_agricultureproperty_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regesteruser',
            name='Paddress',
        ),
        migrations.RemoveField(
            model_name='regesteruser',
            name='Pcity',
        ),
        migrations.RemoveField(
            model_name='regesteruser',
            name='Pcountry',
        ),
        migrations.RemoveField(
            model_name='regesteruser',
            name='Ppincode',
        ),
        migrations.RemoveField(
            model_name='regesteruser',
            name='Pstate',
        ),
        migrations.AddField(
            model_name='agent',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='user_cvs/'),
        ),
    ]
