# Generated by Django 5.1.6 on 2025-11-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_remove_regesteruser_paddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessforsale',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessforsale',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
