# Generated by Django 5.1.6 on 2025-11-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_businessforsale_bathrooms_businessforsale_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproperty',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='holidayproperty',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='residentialproperty',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
