# Generated by Django 5.1.6 on 2025-11-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0005_commercialproperty_currency_holidayproperty_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgproperty',
            name='area_unit',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agricultureproperty',
            name='area_unit',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='agricultureproperty',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='businessforsale',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
