# Generated by Django 5.1.6 on 2025-11-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0007_agricultureproperty_payment_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessforsale',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
