# Generated by Django 5.1.6 on 2025-11-24 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0008_businessforsale_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricultureproperty',
            name='RCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pro.realestatecompany'),
        ),
        migrations.AddField(
            model_name='businessforsale',
            name='RCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pro.realestatecompany'),
        ),
        migrations.AddField(
            model_name='commercialproperty',
            name='RCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pro.realestatecompany'),
        ),
        migrations.AddField(
            model_name='holidayproperty',
            name='RCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pro.realestatecompany'),
        ),
        migrations.AddField(
            model_name='pgproperty',
            name='RCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pro.realestatecompany'),
        ),
        migrations.AddField(
            model_name='residentialproperty',
            name='RCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pro.realestatecompany'),
        ),
    ]
