# Generated by Django 5.1.6 on 2025-11-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0009_agricultureproperty_rcompany_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='is_360',
        ),
        migrations.AddField(
            model_name='businessforsaleimage',
            name='bathroom_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/bathroom/'),
        ),
        migrations.AddField(
            model_name='businessforsaleimage',
            name='bedroom_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/bedroom/'),
        ),
        migrations.AddField(
            model_name='businessforsaleimage',
            name='exterior_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/exterior/'),
        ),
        migrations.AddField(
            model_name='businessforsaleimage',
            name='floor_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/floor_plan/'),
        ),
        migrations.AddField(
            model_name='businessforsaleimage',
            name='kitchen_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/kitchen/'),
        ),
        migrations.AddField(
            model_name='businessforsaleimage',
            name='living_room_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/living_room/'),
        ),
        migrations.AddField(
            model_name='businessforsaleimage',
            name='location_map_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/location_map/'),
        ),
        migrations.AddField(
            model_name='businessforsaleimage',
            name='master_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/master_plan/'),
        ),
        migrations.AddField(
            model_name='holidaypropertyimage',
            name='bathroom_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/bathroom/'),
        ),
        migrations.AddField(
            model_name='holidaypropertyimage',
            name='bedroom_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/bedroom/'),
        ),
        migrations.AddField(
            model_name='holidaypropertyimage',
            name='exterior_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/exterior/'),
        ),
        migrations.AddField(
            model_name='holidaypropertyimage',
            name='floor_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/floor_plan/'),
        ),
        migrations.AddField(
            model_name='holidaypropertyimage',
            name='kitchen_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/kitchen/'),
        ),
        migrations.AddField(
            model_name='holidaypropertyimage',
            name='living_room_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/living_room/'),
        ),
        migrations.AddField(
            model_name='holidaypropertyimage',
            name='location_map_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/location_map/'),
        ),
        migrations.AddField(
            model_name='holidaypropertyimage',
            name='master_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/master_plan/'),
        ),
        migrations.AddField(
            model_name='pgpropertyimage',
            name='bathroom_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/bathroom/'),
        ),
        migrations.AddField(
            model_name='pgpropertyimage',
            name='bedroom_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/bedroom/'),
        ),
        migrations.AddField(
            model_name='pgpropertyimage',
            name='exterior_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/exterior/'),
        ),
        migrations.AddField(
            model_name='pgpropertyimage',
            name='floor_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/floor_plan/'),
        ),
        migrations.AddField(
            model_name='pgpropertyimage',
            name='kitchen_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/kitchen/'),
        ),
        migrations.AddField(
            model_name='pgpropertyimage',
            name='living_room_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/living_room/'),
        ),
        migrations.AddField(
            model_name='pgpropertyimage',
            name='location_map_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/location_map/'),
        ),
        migrations.AddField(
            model_name='pgpropertyimage',
            name='master_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/master_plan/'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='bathroom_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/bathroom/'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='bedroom_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/bedroom/'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='exterior_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/exterior/'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='floor_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/floor_plan/'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_360',
            field=models.ImageField(blank=True, null=True, upload_to='holiday/images/360/'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='kitchen_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/kitchen/'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='living_room_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/living_room/'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='location_map_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/location_map/'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='master_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/master_plan/'),
        ),
    ]
