# Generated by Django 5.2.5 on 2025-11-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0010_remove_propertyimage_is_360_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproperty',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commercialproperty',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialproperty',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialproperty',
            name='view',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
