# Generated by Django 5.2.5 on 2025-11-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0011_commercialproperty_balcony_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessforsale',
            name='locality',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
