# Generated by Django 5.2.5 on 2025-11-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0012_alter_businessforsale_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculturepropertyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='agriculture/images/'),
        ),
        migrations.AlterField(
            model_name='agriculturepropertyimage',
            name='image_360',
            field=models.ImageField(blank=True, null=True, upload_to='agriculture/images/360/'),
        ),
        migrations.AlterField(
            model_name='agriculturepropertyimage',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='agriculture/videos/'),
        ),
        migrations.AlterField(
            model_name='businessforsaleimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business/images/'),
        ),
        migrations.AlterField(
            model_name='businessforsaleimage',
            name='image_360',
            field=models.ImageField(blank=True, null=True, upload_to='business/images/360/'),
        ),
        migrations.AlterField(
            model_name='businessforsaleimage',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='business/videos/'),
        ),
        migrations.AlterField(
            model_name='pgpropertyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pg/images/'),
        ),
        migrations.AlterField(
            model_name='pgpropertyimage',
            name='image_360',
            field=models.ImageField(blank=True, null=True, upload_to='pg/images/360/'),
        ),
        migrations.AlterField(
            model_name='pgpropertyimage',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='pg/videos/'),
        ),
    ]
