# Generated by Django 5.2.5 on 2025-11-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0013_alter_agriculturepropertyimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricultureproperty',
            name='locality',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='holidayproperty',
            name='locality',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pgproperty',
            name='locality',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
