# Generated by Django 5.2.5 on 2025-11-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0015_alter_agricultureproperty_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricultureproperty',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
