# Generated by Django 5.2.5 on 2025-11-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0016_alter_agricultureproperty_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricultureproperty',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='agricultureproperty',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
