# Generated by Django 5.2.5 on 2025-11-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0017_alter_agricultureproperty_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricultureproperty',
            name='total_area',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
    ]
