# Generated by Django 5.2.5 on 2025-11-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0018_alter_agricultureproperty_total_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricultureproperty',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
